"""Add GitHub fields to McpServer

Revision ID: af98e9057b01
Revises: 
Create Date: 2026-06-11 21:00:40.413419+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af98e9057b01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('github_url', sa.String(length=1024), nullable=True))
    op.add_column('mcp_servers', sa.Column('install_command', sa.String(length=1024), nullable=True))
    op.add_column('mcp_servers', sa.Column('working_dir', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'working_dir')
    op.drop_column('mcp_servers', 'install_command')
    op.drop_column('mcp_servers', 'github_url')
    # ### end Alembic commands ###
